version: '3'
services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    environment:
      - proposerId=1
      - acceptors__nodes=["node1:8081","node2:8081","node3:8081"]
      - acceptors__quorum=2
    networks:
      - ogorodnet
    ports:
      - 8080:8080
  node2:
    build: .
    container_name: node2
    hostname: node2
    environment:
      - proposerId=2
      - acceptors__nodes=["node1:8081","node2:8081","node3:8081"]
      - acceptors__quorum=2
    networks:
      - ogorodnet
  node3:
    build: .
    container_name: node3
    hostname: node3
    environment:
      - proposerId=3
      - acceptors__nodes=["node1:8081","node2:8081","node3:8081"]
      - acceptors__quorum=2
    networks:
      - ogorodnet
networks:
  ogorodnet:
    driver: bridge
