# TODO rewrite
version: '3'
services:
  proposer1:
    build: node-proposer
    privileged: true
    container_name: proposer-1
    hostname: proposer-1
    tmpfs:
      - /gryadka/logs
    networks:
      - gryadkanet
  proposer2:
    build: node-proposer
    privileged: true
    container_name: proposer-2
    hostname: proposer-2
    tmpfs:
      - /gryadka/logs
    networks:
      - gryadkanet
  acceptor1:
    build: node-acceptor
    privileged: true
    container_name: acceptor-1
    hostname: acceptor-1
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
  acceptor2:
    build: node-acceptor
    privileged: true
    container_name: acceptor-2
    hostname: acceptor-2
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
  acceptor3:
    build: node-acceptor
    privileged: true
    container_name: acceptor-3
    hostname: acceptor-3
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
networks:
  gryadkanet:
    driver: bridge